# Generated by Django 3.0.8 on 2020-08-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzone', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='regdate',
            field=models.CharField(default='07/08/2020', max_length=20),
            preserve_default=False,
        ),
    ]
